from src.grammar.feature_models import FeaturesModel, FeatureModel, FeatureListModel, save_to_file


class IsSyllable(FeatureModel):
    label: str = 'syl'


class IsStress(FeatureModel):
    label: str = 'stress'


class IsCons(FeatureModel):
    label: str = 'cons'


class IsHigh(FeatureModel):
    label: str = 'high'


class IsLow(FeatureModel):
    label: str = 'low'


class IsPharyngeal(FeatureModel):
    label: str = 'phar'


smh_feature_table = FeaturesModel(
    feature=[
        IsSyllable(),
        IsStress(),
        IsCons(),
        IsHigh(),
        IsLow(),
        IsPharyngeal(),
    ],
    feature_table=[
        FeatureListModel(
            label="p",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="b",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="t",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="d",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="k",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="g",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="ʔ",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="f",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="v",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="s",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="z",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="ʃ",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="ʒ",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="χ",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="ħ",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal(value=True)
            ]
        ),
        FeatureListModel(
            label="ʕ",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal(value=True)
            ]
        ),
        FeatureListModel(
            label="h",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="m",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="n",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="l",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="j",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(value=True),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="a",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="e",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="i",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(),
                IsHigh(value=True),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="o",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(),
                IsHigh(),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="u",
            features=[
                IsSyllable(value=True),
                IsStress(),
                IsCons(),
                IsHigh(value=True),
                IsLow(),
                IsPharyngeal()
            ]
        ),
        FeatureListModel(
            label="'",
            features=[
                IsSyllable(),
                IsStress(value=True),
                IsCons(),
                IsHigh(),
                IsLow(value=True),
                IsPharyngeal()
            ]
        ),

    ],
)

if __name__ == '__main__':
    save_to_file(smh_feature_table, 'features_new')
